--  LIST NUMBER OF RECORDS WITH THE SAME SCORE
-- RESULTS SHOULD DISPLAY SCORE
-- LABEL NUMBER OF RECORDS FOR THIS `SCORE` WITH `NUMBER`
-- SHOULD BE SORTED OUT IN DESC ORDER
SELECT score, COUNT(*) as number FROM second_table GROUP BY score ORDER BY score DESC;